### ISSUE TITLE
Host genome reference format

### ISSUE THREAD

**Issue by danross509** [metagenome-atlas/Tutorial#15]
Hi, I think I'm having trouble specifying a host genome. I've listed it in the contaminants (see below), but the results suggest that none of the reads were mapped to it, nor removed.

contaminant_references:
  PhiX: /data/users/danross/databases/phiX174_virus.fa
  Acer: /data/users/danross/refGens/acersaccharum/GCA_030490815.1/GCA_030490815.1_UCONN_Acsa_1.0_genomic.fna

The Acer (host) reference genome is comprised of 388 scaffolds, is this what's causing the problem?

Thanks,
David

**Comment by SilasK** [comment]
There are one or two log files

                sterr="{sample}/logs/QC/decontamination.err",

                stout="{sample}/logs/QC/decontamination.log",


Donthey mention that no reads were mapped to the host genome?

Could ot be that none were in the metagenome?

**Comment by danross509** [comment]
Hi, sorry I thought I'd closed the issue. I did find after that it had successfully mapped reads to the host genome, just so few that it wasn't apparent from the graphs, only when we read the file it was specified in

**Comment by SilasK** [comment]
Thank ou for the feedback. 
In stats or reports, there should be a table with the numbers to check.
