### ISSUE TITLE
Broken link to view notebook

### ISSUE THREAD

**Issue by skembel** [metagenome-atlas/Tutorial#4]
At the end of Tutorial part 1, it's stated 
> You can always have a look at the notebook to see what would be the output.

The [link ](https://github.com/metagenome-atlas/Tutorial/blob/master/scripts/Differential_abundance.ipynb) to view the notebook is broken and gives a 404.

**Comment by SilasK** [comment]
Thank you for the note: I'm currently rewriting the Tutorial. You can have a look here: https://metagenome-atlas.shinyapps.io/Part2/ 

The jupyter notebooks are [here](https://github.com/metagenome-atlas/Tutorial/tree/master/Python)

**Comment by SilasK** [comment]
You can also have a look at the part  1
https://metagenome-atlas.shinyapps.io/Part1
